In [ ]:
pip install numpy

In [7]:
import numpy as np

Array = np.arange(1,21)
print (Array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
np.sum(Array)

np.int64(210)

In [9]:
np.mean(Array)

np.float64(10.5)

In [10]:
np.median(Array)

np.float64(10.5)

In [11]:
np.std(Array)

np.float64(5.766281297335398)

In [12]:
np.where(Array> 10)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)

In [13]:
array = np.arange(1,17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
np.transpose(array)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [17]:
row_sum = array.sum(axis=1)
col_sum = array.sum(axis=0)

print(row_sum)
print(col_sum)

[10 26 42 58]
[28 32 36 40]


In [23]:
array3 = np.random.randint(1,21, size=(3,3))
array4 = np.random.randint(1,21, size=(3,3))
print(array3)
print(array4)

[[15  4 15]
 [ 1  6  2]
 [20  7  6]]
[[ 2 15 14]
 [ 6 10 13]
 [19 18  2]]


In [28]:
print(array3+array4)
print(array3-array4)
print(array3*array4)

[[17 19 29]
 [ 7 16 15]
 [39 25  8]]
[[ 13 -11   1]
 [ -5  -4 -11]
 [  1 -11   4]]
[[ 30  60 210]
 [  6  60  26]
 [380 126  12]]


In [30]:
print(array3 @ array4)

[[339 535 292]
 [ 76 111  96]
 [196 478 383]]


In [39]:
array5 = np.arange(1,13)
array6 = array5.reshape(3,4)
array6

array7 = array6[:2,2:]
array7

array([[3, 4],
       [7, 8]])